support python 3.8 by using future.__annotations__ (#111)
* support python 3.8 by using typing.List

only a few typing hints had `list`, so this change is rather minimal

* Fix license/classifiers metadata in setup.cfg

If you try to upload this to pypi, its rejected with the error:
WARNING  Error during upload. Retry with the --verbose option for more details.
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/
         Invalid value for classifiers.
         Error: Classifier 'License = file : LICENSE' is not a valid classifier.

Fix comes from here:
https://setuptools.pypa.io/en/latest/userguide/declarative_config.html#metadata

* Revert "support python 3.8 by using typing.List"

This reverts commit 033c1ca6393b4af9c0eccae8f334f82a7e89e11e.

* use __future__.annotations instead of importing List